- hosts: all
  become: yes
  tasks:
    - name: install zabbix repos
      shell: wget https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-1+ubuntu20.04_all.deb

    - name: dpkg
      shell: dpkg -i zabbix-release_6.0-1+ubuntu20.04_all.deb

    - name: install package  
      apt:
        name:
          - ssh
          - zabbix-server-pgsql
          - zabbix-frontend-php
          - php7.4-pgsql
          - zabbix-apache-conf
          - zabbix-agent
          - postgresql

    - name: create db
      postgresql_db:
        name: zabbix

    - name: create user mail
      postgresql_user:
        db: zabbix
        name: zabbix
        password: devdev123

    - name: configure db
      shell: zcat /usr/share/doc/zabbix-server-pgsql*/create.sql.gz | sudo -u zabbix psql zabbix
